apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sheska-redis.fullname" . }}-data
  labels:
    {{- include "sheska-redis.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
