apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sheska-postgres.fullname" . }}-initdb
  labels:
    {{- include "sheska-postgres.labels" . | nindent 4 }}
data:
  01-extensions.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
