image:
  repository: redis
  tag: "8-alpine"
  pullPolicy: IfNotPresent

storage:
  size: 2Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 2Gi

nodeSelector:
  kubernetes.io/hostname: hash-n100-1
