apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sheska-api-secret
  namespace: sheska
spec:
  encryptedData:
    DATABASE_URL: AgByH/pbVD9BHqV0f2Mb0bM/Z303WBRifnzq4v9yWX3oRLPVhPSLT7mbUVjigXT8boy6BrTkodK5N/WtCUcghAwbai5vHG7AqG6bzGPFSepvvyzWeyfbSUZbS9wJfqf4Vuz+YWW/6as5aFo1r3nd/ly2+Nk1eC1MUmXIGhTWf+s9A/WGbcCKR+AQXHUKYQb8RnBuXC//lMeZ+dYp4uoMFFf3D99Hi3JLYMXCKRlqm0hmzDAFKN8FHu1bDVvo2NUohH46wVzci3A5pgfXfB0jTlSH6V4+pQzMrVH5YNbO4KSNsEVP+Vgh636Cknxc8Z13P622hzMbDfP4Rl3pZIn7sMs08d2lSGD6a0mbmr4mhyxjWoeHn6eXq3oF5Anmo/23/J338hXtZLtUB5ifFrpgucVmWY0zkD35tBPwnB0U89Y7fvgIVyLXoS2JhLED8Xc7aQsE3zKghupdFYdgtyU3/O5modntzVSNYGvtb/HvlS07eyLkybGnhQ+drR+UrBg18mb42qGxARe7BNeHO6XBtE7EVCRE6WygIAy6i2TnpqRW9fSkVN/O9UC1ZFYVOTzKg7qYfZajDNkoeFpgBc5sWhYPEt6murC1eHtv1uxLX0dBMb8C8CwT7ceoY2/7RdCqsw3Qd5OzEmYVa7xZV+4c9xYtQU9YODEgoufLFnwvTQeDlc01amuecNVxNg+B5w17U6UBzv5X7wIZ6F7F3GaL77UeLqMrkXw9PmhuW6BWh9gs0YkLYS/aQaWSKPuSd2v+0OWvA3H2KcUyirAsYdo=
    REDIS_URL: AgCmkMS+WxiLaDzlYxX0Y7jpw46JYouRuy5JuIfrsbFzWhZ8vaX5Bx3igP4R1UVrnrwT96GpwyE3vPyUMyewmDPZIEzxnolYY9hu4ocap1ru5WedVoTvt8V3rwMgy0nFdUIAJVLxaxdUyvSHZMe1zKJ0b1tHis/1JFHWVn1/YlP/W1RBrlwGRHjKSenQ36mPY/VlQR+uK2eG8xvzRBVg6kUEwBEzQOheI9s2KP/gj7ASsYEDLb2tjhYB9/piBDTHmZgOC1Q14vtqRKdYJ7yucUgsJ0EP47HSBseCLloLAB5wqX/U3ai24bokjv4yZJ4NFbFgyDjnlP5pPPlghQW2m94ohXEaf5RVxnOm3ur+smBU0ETF8nxhByY260Ok8H0Hg5NBjdyt+5C3qeqp1oAEnQ4G6m3xXDE1RoBv+8jKDyPZyDTKkVblKskiB8/hrFa14PW1KuVc+OdOwqCYFCjaOFE1ZiZN8tpUpiUYdIHPrrZhc8mhtnZZXCIwH1jeSpvkwCFdr3zgu5przcD8fpK+vsPdHbWBt8FU0zaUZsPmxQ3YqJvJ+MoQz7wdxmn4b5PzRXDKolPhXR+YKXNrjIAEq7bv819jFi9/Z2uSK7wuqDCQ7eX9TPRLwS2W5UgAeQjgRl/4uyfE559eKrfIjVvQadX8gjNSWbfwPl4W5SX9rL5hFxbU8cwaotVTL+CCvO4vZMvVzdiVg+6mq4xOBF0WWCWZtJe1ROXDVLyE
  template:
    metadata:
      creationTimestamp: null
      name: sheska-api-secret
      namespace: sheska
    type: Opaque