apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sheska-api
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-manifest-synced.homelab: "C0BV08N8XFC"
    notifications.argoproj.io/subscribe.on-health-degraded.homelab: "C0BV08N8XFC"
    notifications.argoproj.io/subscribe.on-sync-failed.homelab: "C0BV08N8XFC"
    notifications.argoproj.io/subscribe.on-health-suspended.homelab: "C0BV08N8XFC"
    notifications.argoproj.io/subscribe.on-health-missing.homelab: "C0BV08N8XFC"
spec:
  project: sheska
  source:
    repoURL: https://github.com/makeUgreat/sheska.git
    path: deploy/helm/sheska-api
    targetRevision: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: sheska
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
