apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sheska-api
  namespace: argocd
spec:
  project: sheska
  source:
    repoURL: https://github.com/makeUgreat/sheska.git
    path: deploy/helm/sheska-api
    targetRevision: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: sheska
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
