image:
  repository: pgvector/pgvector
  tag: "pg18"
  pullPolicy: IfNotPresent

secret:
  name: sheska-postgres-secret

storage:
  size: 100Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1500m
    memory: 4Gi

nodeSelector:
  kubernetes.io/hostname: hash-n150-1
