replicaCount: 2
secret:
  name: sheska-api-secret
image:
  repository: willom2c/sheska-api
  pullPolicy: IfNotPresent
  tag: "sha-a5e8c8af5c5210e8f72de0f52d382e5f536f4743"
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: api-sheska.meogle.co.kr
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  requests:
    memory: 512Mi
embedding:
  baseUrl: http://sheska-ollama.sheska.svc.cluster.local:11434
nodeSelector: {}
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - hash-n97-1
topologySpread:
  enabled: true
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
  matchLabelKeys:
    - pod-template-hash
