replicaCount: 2
secret:
  name: sheska-api-secret
image:
  repository: willom2c/sheska-api
  pullPolicy: IfNotPresent
  tag: "sha-49b989d4e5615ce0e431c4d69225288816827fee"
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: api-sheska.meogle.co.kr
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  requests:
    memory: 512Mi
embedding:
  baseUrl: http://sheska-embedder.sheska.svc.cluster.local:11434
otel:
  exporterOtlpEndpoint: http://alloy.observability.svc.cluster.local:4318
nodeSelector: {}
tolerations: []
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: NotIn
              values:
                - hash-n97-1
topologySpread:
  enabled: true
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule
  matchLabelKeys:
    - pod-template-hash
