import { describe, expect, it } from 'vitest';
import { generateThemeCss } from './generate-theme-css.mjs';

const baseTokens = {
  color: {
    $type: 'color',
    surface: {
      $value: {
        colorSpace: 'srgb',
        components: [0, 0, 0],
        hex: '#000000',
      },
    },
    accent: {
      $value: '{color.surface}',
    },
  },
  typography: {
    'font-family': {
      sans: {
        $type: 'fontFamily',
        $value: ['Geist', 'Arial', 'sans-serif'],
      },
      mono: {
        $type: 'fontFamily',
        $value: ['JetBrains Mono', 'monospace'],
      },
    },
    body: {
      $type: 'typography',
      $value: {
        fontFamily: '{typography.font-family.sans}',
        fontSize: '16px',
        fontWeight: '400',
        lineHeight: '1.6',
      },
    },
  },
  radius: {
    default: {
      $value: '0.25rem',
    },
  },
  spacing: {
    unit: {
      $value: '4px',
    },
    'container-max': {
      $value: '1280px',
    },
  },
};

describe('generateThemeCss', () => {
  it('generates Tailwind theme variables from design tokens', () => {
    expect(generateThemeCss(baseTokens)).toBe(
      `/* This file is generated by \`pnpm tokens:build\`. Do not edit directly. */
@theme static {
  --color-surface: #000000;
  --color-accent: #000000;

  --font-sans: "Geist", "Arial", sans-serif;
  --font-mono: "JetBrains Mono", monospace;

  --text-body: 16px;
  --text-body--line-height: 1.6;
  --text-body--font-weight: 400;

  --radius-default: 0.25rem;

  --spacing-unit: 4px;
  --container-content: 1280px;
}
`,
    );
  });

  it('throws when a token reference cannot be resolved', () => {
    expect(() => {
      generateThemeCss({
        ...baseTokens,
        color: {
          broken: {
            $value: '{color.missing}',
          },
        },
      });
    }).toThrow('Unknown token reference: {color.missing}');
  });
});
