services:
  db:
    image: postgres:18
    container_name: sheska.development.db
    environment:
      POSTGRES_DB: sheska
      POSTGRES_USER: sheska
      POSTGRES_PASSWORD: sheska
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - sheska_development_db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sheska -d sheska']
      start_period: 10s
      start_interval: 1s
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  sheska_development_db: