services:
  db:
    image: postgres:18
    container_name: sheska.development.db
    environment:
      POSTGRES_DB: sheska
      POSTGRES_USER: sheska
      POSTGRES_PASSWORD: sheska
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - sheska_development_db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sheska -d sheska']
      start_period: 10s
      start_interval: 1s
      interval: 2s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: sheska.development.redis
    ports:
      - '6379:6379'
    volumes:
      - sheska_development_redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      start_period: 5s
      start_interval: 1s
      interval: 2s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: sheska.development.ollama
    ports:
      - '11434:11434'
    volumes:
      - sheska_development_ollama:/root/.ollama
    healthcheck:
      test: ['CMD', 'ollama', 'list']
      start_period: 15s
      start_interval: 2s
      interval: 5s
      timeout: 5s
      retries: 10

  ollama-init:
    image: ollama/ollama:latest
    container_name: sheska.development.ollama-init
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: ['ollama', 'pull', 'qwen3-embedding:0.6b']
    environment:
      - OLLAMA_HOST=http://ollama:11434
    restart: no

volumes:
  sheska_development_db:
  sheska_development_redis:
  sheska_development_ollama:
